# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-27 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16, verbose_name='\u7ec4\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u6807\u9898')),
                ('url', models.CharField(max_length=64, verbose_name='\u542b\u6b63\u5219URL')),
                ('is_menu', models.BooleanField(verbose_name='\u662f\u5426\u662f\u83dc\u5355')),
                ('code', models.CharField(max_length=16, verbose_name='\u4ee3\u7801')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Group', verbose_name='\u6240\u5c5e\u7ec4')),
            ],
            options={
                'verbose_name_plural': '\u6743\u9650\u8868',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='\u5177\u6709\u7684\u6240\u6709\u6743\u9650')),
            ],
            options={
                'verbose_name_plural': '\u89d2\u8272\u8868',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=64, verbose_name='\u5bc6\u7801')),
                ('email', models.CharField(max_length=32, verbose_name='\u90ae\u7bb1')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='\u5177\u6709\u7684\u6240\u6709\u89d2\u8272')),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u8868',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='\u6240\u5c5e\u83dc\u5355'),
        ),
    ]
