# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20180928_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
