# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-19 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_role_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=13088, verbose_name='\u624b\u673a\u53f7\u7801'),
            preserve_default=False,
        ),
    ]
