# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-19 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
    ]
