# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20181019_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag',
            field=models.IntegerField(default=0, help_text='\u9ed8\u8ba40,0\u4ee3\u8868\u666e\u901a\u7528\u6237,1\u4ee3\u8868\u7ba1\u7406\u5458'),
        ),
    ]
