# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-19 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_user_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0, help_text='\u9ed8\u8ba41,0\u4ee3\u8868\u7981\u7528,1\u4ee3\u8868\u542f\u7528'),
        ),
    ]
