# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-19 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20181019_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1, help_text='\u9ed8\u8ba41,0\u4ee3\u8868\u7981\u7528,1\u4ee3\u8868\u542f\u7528'),
        ),
    ]
