# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20181019_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag_delete',
            field=models.IntegerField(default=1, help_text='\u9ed8\u8ba41,0\u4ee3\u8868\u5df2\u5220\u9664\u7528\u6237,1\u4ee3\u8868\u6b63\u5e38\u7528\u6237'),
        ),
    ]
