# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-24 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20181024_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='flag',
            field=models.IntegerField(default=0, help_text='\u9ed8\u8ba40,0\u4ee3\u8868\u542f\u7528,1\u4ee3\u8868\u7981\u7528'),
        ),
        migrations.AddField(
            model_name='permission',
            name='flag',
            field=models.IntegerField(default=0, help_text='\u9ed8\u8ba40,0\u4ee3\u8868\u542f\u7528,1\u4ee3\u8868\u7981\u7528'),
        ),
    ]
