# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-24 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_auto_20181024_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='flag',
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.IntegerField(default=1, help_text='\u9ed8\u8ba41,0\u4ee3\u8868\u7981\u7528,1\u4ee3\u8868\u542f\u7528'),
        ),
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.IntegerField(default=1, help_text='\u9ed8\u8ba41,0\u4ee3\u8868\u7981\u7528,1\u4ee3\u8868\u542f\u7528'),
        ),
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.IntegerField(default=1, help_text='\u9ed8\u8ba41,0\u4ee3\u8868\u7981\u7528,1\u4ee3\u8868\u542f\u7528'),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.IntegerField(default=1, help_text='\u9ed8\u8ba41,0\u4ee3\u8868\u7981\u7528,1\u4ee3\u8868\u542f\u7528'),
        ),
        migrations.AlterField(
            model_name='role',
            name='flag',
            field=models.IntegerField(default=0, help_text='\u9ed8\u8ba40,0\u4ee3\u8868\u666e\u901a\u89d2\u8272,1\u4ee3\u8868\u7ba1\u7406\u5458\u89d2\u8272'),
        ),
    ]
